apiVersion: apps/v1
kind: Deployment
metadata:
  name: fjord-deployment
  namespace: stock
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: fjord 
  template:
    metadata:
      annotations:
        git-tag: "v15"
      labels:
        app: fjord 
    spec:
      restartPolicy: Always
      imagePullSecrets:
        - name: regcred
      containers:
        - name: fjord 
          image: artifacts.tekuro.io/fjord:latest
          env:
            - name: INFLUXDB_URL
              valueFrom:
                secretKeyRef:
                  name: influxdb-secrets
                  key: url
            - name: INFLUXDB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: influxdb-secrets
                  key: token
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: stock-poller-config
                  key: REDIS_HOST
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: stock-poller-config
                  key: REDIS_PORT
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis
                  key: redis-password
