name: Fjord CI

on:
  push:
    branches: [ "main" ]
    paths-ignore: [ "README.md", "deployment/**" ]

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  IMAGE_NAME: artifacts.tekuro.io/fjord:latest

jobs:

  build-and-deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Build the Docker image
      run: docker build -t ${{ env.IMAGE_NAME }} .
      
    - name: Login to Tekuro Artifacts
      uses: docker/login-action@v1
      with:
        registry: artifacts.tekuro.io
        username: ${{ env.DOCKER_USERNAME }}
        password: ${{ env.DOCKER_PASSWORD }}
        
    - name: Push Docker image
      run: docker push ${{ env.IMAGE_NAME }}

    - name: Release
      run: |
        cd deployment
        SHA=${{ github.sha }}
        sed -i "/annotations:/,/^[^[:space:]]/ s/gh-actions-sha:.*/gh-actions-sha: \"$SHA\"/" deployment.yaml
        git config --global user.name 'Github Actions'
        git config --global user.email 'actions@github.com'
        git add deployment.yaml
        git commit -m "Release $SHA"
        git push
    
