name: Fjord CI

on:
  push:
    branches: [ "main" ]
    paths-ignore: [ "README.md", "deployment/**" ]

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  IMAGE_NAME: artifacts.tekuro.io/fjord:latest

jobs:

  build-and-deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Build the Docker image
      run: docker build -t ${{ env.IMAGE_NAME }} .
      
    - name: Login to Tekuro Artifacts
      uses: docker/login-action@v1
      with:
        registry: artifacts.tekuro.io
        username: ${{ env.DOCKER_USERNAME }}
        password: ${{ env.DOCKER_PASSWORD }}
        
    - name: Push Docker image
      run: docker push ${{ env.IMAGE_NAME }}

    - name: Release
      run: |
        cd deployment

        git fetch --tags

        LATEST_TAG=$(git tag -l 'v*' --sort=-v:refname | head -n1)
        
        if [[ -z "$LATEST_TAG" ]]; then
          NEW_TAG="v1"
        else
          NUM=${LATEST_TAG#v}
          NUM=$((NUM + 1))
          NEW_TAG="v$NUM"
        fi

        sed -i "/annotations:/,/^[^[:space:]]/ s/gh-actions-sha:.*/gh-actions-sha: \"$NEW_TAG\"/" deployment.yaml
        git config --global user.name 'Github Actions'
        git config --global user.email 'actions@github.com'


        git checkout -B release/$NEW_TAG
        git add deployment.yaml
        git commit -m "Release $NEW_TAG" || echo "No changes to commit"
        git push --force origin release/$NEW_TAG

        git tag $NEW_TAG
        git push origin $NEW_TAG
